/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inspiry_barcodeupdate_BarCodeSerialUpdate */

#ifndef _Included_com_inspiry_barcodeupdate_BarCodeSerialUpdate
#define _Included_com_inspiry_barcodeupdate_BarCodeSerialUpdate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inspiry_barcodeupdate_BarCodeSerialUpdate
 * Method:    getVersionNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inspiry_barcodeupdate_BarCodeSerialUpdate_getVersionNative
  (JNIEnv *, jobject);
  
/*
 * Class:     com_inspiry_barcodeupdate_BarCodeSerialUpdate
 * Method:    getTargetHardwareNameNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inspiry_barcodeupdate_BarCodeSerialUpdate_getTargetHardwareNameNative
  (JNIEnv *, jobject);

/*
 * Class:     com_inspiry_barcodeupdate_BarCodeSerialUpdate
 * Method:    updateNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_inspiry_barcodeupdate_BarCodeSerialUpdate_updateNative
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_inspiry_barcodeupdate_BarCodeSerialUpdate
 * Method:    openNative
 * Signature: (Ljava/lang/Object;Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_inspiry_barcodeupdate_BarCodeSerialUpdate_openNative
  (JNIEnv *, jobject, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     com_inspiry_barcodeupdate_BarCodeSerialUpdate
 * Method:    closeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_inspiry_barcodeupdate_BarCodeSerialUpdate_closeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_inspiry_barcodeupdate_BarCodeSerialUpdate
 * Method:    nativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_inspiry_barcodeupdate_BarCodeSerialUpdate_nativeClassInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
